# Generated by Django 5.0.2 on 2024-03-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, null=True)),
                ('student_class', models.CharField(max_length=10, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='student_profiles/')),
            ],
        ),
    ]
